<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\dist\$(Configuration)\nativePC\plugins\CSharp\MhwDpsMeter\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpPluginLoader.Core" Version="0.0.7.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Addresses\*.map">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
